# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run End-to-End Tests in Staging

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run end-to-end tests
        env:
          SITE_URL: ${{ secrets.STAGING_URL }}
        uses: DevExpress/testcafe-action@latest
        with:
          skip-install: true
          args: "chrome src/tests/e2e/"
