# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Install Node & Run Test Suites

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Install Dependencies & Run Test Suites
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Dependencies with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        run: npm install

      - name: Run unit tests
        run: npm run tests:unit

      - name: Run end-to-end tests
        uses: DevExpress/testcafe-action@latest
        with:
          skip-install: true
          args: "chrome src/tests/e2e/"
